# Generated by Django 6.0.3 on 2026-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(default='Order Placed', max_length=50)),
            ],
        ),
    ]
