# Generated by Django 6.0.3 on 2026-03-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Order Placed', max_length=50),
        ),
    ]
